### ISSUE TITLE
App functionality

### ISSUE THREAD

**Issue by PeppeL-G** [PeppeL-G/friendos#1]
We need to decide what funcitonality our app should contain. Any ideas?

@Sigvard84

**Comment by Sigvard84** [comment]
Maybe we can have a list of friends? @PeppeL-G

**Comment by PeppeL-G** [comment]
And also showing more info about a friend?

**Comment by Sigvard84** [comment]
Sounds really good!

**Comment by PeppeL-G** [comment]
So, something like this?

![use-case-diagram](https://user-images.githubusercontent.com/188492/150800396-276bcd05-e4de-4607-a8c0-0314a69bf158.jpeg)

**Comment by Sigvard84** [comment]
Looks awesome!
