### ISSUE TITLE
Implement list of friends

### ISSUE THREAD

**Issue by PeppeL-G** [PeppeL-G/friendos#4]
On one page, all friends should be listed.

**Comment by PeppeL-G** [comment]
What package name should we use? @Sigvard84

**Comment by Sigvard84** [comment]
Let's use se.ju.friendos

**Comment by PeppeL-G** [comment]
How should we store our data? In variables? IN files? In dataabse? @Sigvard84

**Comment by Sigvard84** [comment]
Let's use variables, like JSON or something to start with. Later we can move to database!
